# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b99d667ffbed405b56648208b163e9b51708b705d03658f4e4ce5b094ca20ee536528a13fba2dcad3e1be97455baf1d8ad749e35b54bef490829c8cf08c6a950

test:
  secret_key_base: 224769d43805ddc4a7af78793f7e5877881838986bffe4a29fe5fe80e93486d5feff0912272d72848c12e0e4a0b7b23e4535d5e4a50b2413682c96cbe32a6837

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
